// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import SelectAllCheckboxesController from "./select_all_checkboxes_controller"
application.register("select-all-checkboxes", SelectAllCheckboxesController)

import { Modal } from "tailwindcss-stimulus-components"
application.register('modal', Modal)